export const LOADING_BOARDS = 'LOADING_BOARDS';
export const LOAD_BOARDS_SUCCESS = 'LOAD_BOARDS_SUCCESS';
export const LOAD_BOARDS_FAIL = 'LOAD_BOARDS_FAIL';
export const ADD_BOARD_SUCCESS = 'ADD_BOARD_SUCCESS';
export const ADD_BOARD_FAIL = 'ADD_BOARD_FAIL';
export const ADD_BOARD_NORMALISE = 'ADD_BOARD_NORMALISE';
